services:
  deeplx:
    build: .
    image: dlx-local:latest
    restart: always
    ports:
      - "1188:1188"
    environment:
      - PROXY=${PROXY:?set PROXY in .env}
      - RESIN_ACCOUNT=${RESIN_ACCOUNT:-dlx}
      # - TOKEN=helloworld
      # - DL_SESSION=xxxxxx
